// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcgrgauiPU15m0DMKjcSiGt0VPDEjJlPo',
    appId: '1:988254097528:web:8f89fc5fe2b7f4b7af9d8d',
    messagingSenderId: '988254097528',
    projectId: 'fir-app-v2-751f6',
    authDomain: 'fir-app-v2-751f6.firebaseapp.com',
    storageBucket: 'fir-app-v2-751f6.appspot.com',
    measurementId: 'G-FGLQCEE1XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnDJd9Dn__Ag0fAS2_IbHVt7B9iZcKW9o',
    appId: '1:988254097528:android:537a7ea56bea8b4baf9d8d',
    messagingSenderId: '988254097528',
    projectId: 'fir-app-v2-751f6',
    storageBucket: 'fir-app-v2-751f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFaraTHH4y_I3KO5m5qAdHgO0Qkw3UdWA',
    appId: '1:988254097528:ios:581547f65a7eb7b5af9d8d',
    messagingSenderId: '988254097528',
    projectId: 'fir-app-v2-751f6',
    storageBucket: 'fir-app-v2-751f6.appspot.com',
    iosClientId: '988254097528-4go3irlnre1ctt30fmihf223rsndvs5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFaraTHH4y_I3KO5m5qAdHgO0Qkw3UdWA',
    appId: '1:988254097528:ios:b1ebf41a0b5b58adaf9d8d',
    messagingSenderId: '988254097528',
    projectId: 'fir-app-v2-751f6',
    storageBucket: 'fir-app-v2-751f6.appspot.com',
    iosClientId: '988254097528-kom1vobqon2hck348v94m1lup3ea4agf.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoAppV2.RunnerTests',
  );
}
